// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma 7 supports Neon pooled connections for migrations. Use the same
    // endpoint already verified by the Express runtime.
    url: process.env["DATABASE_URL"],
  },
});
